FROM python:3.10
WORKDIR /app
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ ./
EXPOSE 5001
CMD ["watchmedo", "auto-restart", "--patterns=*.py;*.json", "--recursive", "--", "python", "app.py"]