version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000" # Host:Container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=57.129.44.194
      - WDS_SOCKET_PORT=3001
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5001
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
