FROM python:3.10
WORKDIR /app
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ ./
EXPOSE 5001
CMD ["sh", "-c", "if [ \"$FLASK_ENV\" = \"development\" ]; then watchmedo auto-restart --patterns=\"*.py;*.json\" --ignore-patterns=\"db/*\" --recursive -- python app.py; else python app.py; fi"]